#include "motors.h"
#include "pins.h"

Stepper leftStepper(STEPS_PER_REVOLUTION,  MOTOR_1_PIN_1, MOTOR_1_PIN_2, MOTOR_1_PIN_3, MOTOR_1_PIN_4);
Stepper frontStepper(STEPS_PER_REVOLUTION, MOTOR_2_PIN_1, MOTOR_2_PIN_2, MOTOR_2_PIN_3, MOTOR_2_PIN_4);
Stepper rightStepper(STEPS_PER_REVOLUTION, MOTOR_3_PIN_1, MOTOR_3_PIN_2, MOTOR_3_PIN_3, MOTOR_3_PIN_4);
Stepper backStepper(STEPS_PER_REVOLUTION,  MOTOR_4_PIN_1, MOTOR_4_PIN_2, MOTOR_4_PIN_3, MOTOR_4_PIN_4);
